name: finetune_mace_heo
seed: 1
multiheads_finetuning: False
train_file: /home/snw30/rds/hpc-work/heo/heo_relax/data/train.xyz
forces_key: DFT_forces
energy_key: DFT_energy
valid_file: /home/snw30/rds/hpc-work/heo/heo_relax/data/valid.xyz
foundation_model: medium
E0s: foundation
default_dtype: float64
energy_weight: 1.0
forces_weight: 10.0
lr: 0.0001
max_num_epochs: 10
scaling: rms_forces_scaling
batch_size: 5
device: cuda
enable_cueq: True